title: "sam scribbles"
email: samshuwong@gmail.com
description: a home for my memoir-style musings 

baseurl: "/" 
url: "https://thesamwong.github.io" 
twitter_username: hipsterwam
github_username:  thesamwong

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-slate
