title: "sam scribbles"
email: samshuwong@gmail.com
description: >- # This means to ignore newlines until "baseurl:"
  I'm a new technologist who is keen on culture, comedy, and creativity. Detaching my systematic Substack self from my poetic philosophical persona. An alliteration advocate.

  I like when small talk grows into big talk, deep talk, and long talk.

baseurl: "/" 
url: "https://thesamwong.github.io" 
twitter_username: hipsterwam
github_username:  thesamwong

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg

theme: jekyll-theme-slate
