title: "Sam Wong"
email: samshuwong@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Sam's sandbox for technical projects!
baseurl: "/" 
url: "https://thesamwong.github.io" 
twitter_username: hipsterwam
github_username:  thesamwong

sass:
  sass_dir: _sass

icon: ./assets/img/icon.jpg
